kind: pipeline
name: default

steps:
  - name: test
    image: python
    commands:
      - mkdir -p /var/reports
      - ls -lah
      
#  - name: build
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#
#  - name: run
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#      - ./output
